# Generated by Django 6.0.5 on 2026-05-12 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS cashflow;',
            reverse_sql=None,
        ),
        migrations.CreateModel(
            name='PlanningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('end_date', models.DateField()),
                ('average_daily_expenditure', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_budgeted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
            options={
                'db_table': '"cashflow"."plannings"',
            },
        ),
        migrations.CreateModel(
            name='BudgetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('limit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('description', models.CharField(max_length=255)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='infrastructure.planningmodel')),
            ],
            options={
                'db_table': '"cashflow"."budgets"',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(max_length=20)),
                ('cleared', models.BooleanField(default=False)),
                ('cleared_at', models.DateField(blank=True, null=True)),
                ('auto_pay', models.BooleanField(default=False)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='infrastructure.planningmodel')),
            ],
            options={
                'db_table': '"cashflow"."transactions"',
            },
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_date', models.DateField()),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='infrastructure.planningmodel')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.transactionmodel')),
            ],
            options={
                'db_table': '"cashflow"."notifications"',
            },
        ),
    ]
