# Generated by Django 6.0.5 on 2026-05-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_remove_planningmodel_color_budgetmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningmodel',
            name='start_billing_cycle',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='planningmodel',
            name='status',
            field=models.CharField(default='updated', max_length=50),
        ),
    ]
